export enum Role {
  PlatformAdmin = 'PlatformAdmin',
  SuperAdmin = 'Super Admin',
  CompanyAdmin = 'CompanyAdmin',
  Admin = 'Admin',
  Regionalleiter = 'Regionalleiter',
  Filialleiter = 'Filialleiter',
  Restaurantleiter = 'Restaurantleiter',
  Schichtleiter = 'Schichtleiter',
  Service = 'Service',
  Kueche = 'Küche',
  Bar = 'Bar',
  Theke = 'Theke',
  Lager = 'Lager',
  Einkauf = 'Einkauf',
  Buchhaltung = 'Buchhaltung',
  Marketing = 'Marketing',
  Personalabteilung = 'Personalabteilung',
  Reinigung = 'Reinigung',
  Eventmanager = 'Eventmanager',
  Kunde = 'Kunde',
  Tellerwaescher = 'Tellerwäscher',
}
