export interface PermissionDefinition {
  key: string;
  module: string;
  resource: string;
  action: string;
  description: string;
}

const modules = {
  dashboard: ['view'],
  dailyClosings: ['view', 'manage', 'reopen', 'lock'],
  users: ['view', 'create', 'update', 'delete', 'own.view', 'own.update'],
  roles: ['view', 'create', 'update', 'delete', 'permissions.update'],
  companies: ['view', 'create', 'update'],
  regions: ['view', 'create', 'update'],
  locations: ['view', 'create', 'update', 'delete'],
  tables: ['view', 'create', 'update', 'status.update', 'delete'],
  orders: ['view', 'create', 'update', 'cancel'],
  counter: [
    'orders.view',
    'orders.create',
    'orders.update',
    'orders.cancel',
    'orders.pay',
    'orders.complete',
    'pickupDisplay.view',
    'settings.view',
    'settings.update',
    'reports.view',
    'reports.export',
  ],
  kds: ['view', 'manage'],
  reservations: ['view', 'create', 'update', 'delete'],
  inventory: [
    'view',
    'create',
    'update',
    'delete',
    'stock.adjust',
    'inventory.manage',
  ],
  suppliers: ['view', 'create', 'update', 'delete'],
  menuItems: ['view', 'create', 'update', 'delete'],
  recipes: [
    'view',
    'create',
    'update',
    'delete',
    'costing.view',
    'report.export',
  ],
  categories: ['view', 'create', 'update', 'delete'],
  tasks: ['view', 'create', 'update', 'delete'],
  employees: ['view', 'create', 'update', 'delete', 'export'],
  hrDocuments: ['view', 'create', 'update', 'delete'],
  recruiting: ['view', 'create', 'update', 'delete'],
  feedback: ['view', 'create', 'update', 'delete'],
  schedule: ['view', 'create', 'update', 'delete', 'publish'],
  timeTracking: ['view', 'clock', 'correct'],
  absence: ['view', 'request', 'approve'],
  payroll: ['view', 'export'],
  internalMessages: ['view', 'create'],
  reports: ['view', 'export'],
  analytics: ['view'],
  finance: ['view', 'update'],
  accounting: ['view', 'update'],
  marketing: ['view', 'update'],
  customers: ['view', 'create', 'update', 'delete'],
  settings: ['view', 'update'],
  audit: ['view'],
} satisfies Record<string, string[]>;

export const PERMISSION_DEFINITIONS: PermissionDefinition[] = Object.entries(
  modules,
).flatMap(([module, actions]) =>
  actions.map((action) => ({
    key: `${module}.${action}`,
    module,
    resource: module,
    action,
    description: `${module}.${action}`,
  })),
);

export const ALL_PERMISSIONS = PERMISSION_DEFINITIONS.map(
  (permission) => permission.key,
);

const withoutPermissions = (...deniedPrefixes: string[]): string[] =>
  ALL_PERMISSIONS.filter(
    (permission) =>
      !deniedPrefixes.some((prefix) => permission.startsWith(prefix)),
  );

const companyAdminPermissions = withoutPermissions('settings.update');

const regionAdminPermissions = withoutPermissions(
  'audit.view',
  'companies.create',
  'companies.update',
  'regions.create',
  'regions.update',
  'roles.create',
  'roles.update',
  'roles.delete',
  'roles.permissions.update',
  'settings.update',
  'tables.delete',
);

const regionalleiterPermissions = withoutPermissions(
  'audit.view',
  'companies.',
  'regions.create',
  'regions.update',
  'roles.',
  'settings.',
  'tables.delete',
);

const bereichsleiterPermissions = withoutPermissions(
  'audit.view',
  'companies.',
  'regions.create',
  'regions.update',
  'roles.',
  'settings.',
  'locations.create',
  'locations.delete',
  'tables.delete',
);

const filialleiterPermissions = withoutPermissions(
  'audit.view',
  'companies.',
  'regions.',
  'roles.',
  'settings.',
  'locations.create',
  'locations.delete',
  'tables.delete',
);

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  PlatformAdmin: ['*'],
  'Super Admin': ['*'],
  CompanyAdmin: companyAdminPermissions,
  RegionAdmin: regionAdminPermissions,
  Admin: companyAdminPermissions,
  Regionalleiter: regionalleiterPermissions,
  Bereichsleiter: bereichsleiterPermissions,
  Filialleiter: filialleiterPermissions,
  Restaurantleiter: [
    'dashboard.view',
    'users.view',
    'counter.orders.view',
    'counter.orders.create',
    'counter.orders.update',
    'counter.orders.pay',
    'counter.orders.complete',
    'counter.orders.cancel',
    'counter.pickupDisplay.view',
    'counter.settings.view',
    'counter.reports.view',
    'orders.view',
    'orders.update',
    'kds.view',
    'kds.manage',
    'inventory.view',
    'recipes.view',
    'recipes.costing.view',
    'suppliers.view',
    'reports.view',
    'analytics.view',
    'dailyClosings.view',
    'dailyClosings.manage',
    'employees.view',
    'employees.create',
    'employees.update',
    'employees.export',
    'hrDocuments.view',
    'hrDocuments.create',
    'hrDocuments.update',
    'recruiting.view',
    'recruiting.create',
    'recruiting.update',
    'feedback.view',
    'feedback.create',
    'feedback.update',
    'schedule.view',
    'schedule.create',
    'schedule.update',
    'schedule.publish',
    'timeTracking.view',
    'timeTracking.clock',
    'absence.view',
    'absence.request',
    'absence.approve',
    'payroll.view',
  ],
  Schichtleiter: [
    'dashboard.view',
    'tables.view',
    'tables.status.update',
    'counter.orders.view',
    'counter.orders.create',
    'counter.orders.update',
    'counter.orders.pay',
    'counter.orders.complete',
    'counter.orders.cancel',
    'counter.pickupDisplay.view',
    'counter.settings.view',
    'counter.reports.view',
    'orders.view',
    'orders.update',
    'kds.view',
    'kds.manage',
    'tasks.view',
    'dailyClosings.view',
    'dailyClosings.manage',
    'employees.view',
    'hrDocuments.view',
    'feedback.view',
    'feedback.create',
    'schedule.view',
    'schedule.create',
    'schedule.update',
    'timeTracking.view',
    'timeTracking.clock',
    'absence.view',
    'absence.request',
  ],
  Service: [
    'dashboard.view',
    'locations.view',
    'tables.view',
    'tables.status.update',
    'counter.orders.view',
    'counter.orders.create',
    'counter.orders.update',
    'counter.orders.pay',
    'counter.orders.complete',
    'counter.orders.cancel',
    'counter.pickupDisplay.view',
    'counter.settings.view',
    'orders.view',
    'orders.create',
    'orders.update',
    'reservations.view',
    'reservations.create',
    'kds.view',
    'kds.manage',
    'menuItems.view',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'schedule.view',
    'timeTracking.view',
    'timeTracking.clock',
    'absence.view',
    'absence.request',
    'internalMessages.view',
    'internalMessages.create',
    'users.own.view',
    'users.own.update',
    'recipes.view',
  ],
  Küche: [
    'dashboard.view',
    'locations.view',
    'tables.view',
    'counter.orders.view',
    'counter.orders.update',
    'counter.pickupDisplay.view',
    'counter.settings.view',
    'orders.view',
    'orders.update',
    'kds.view',
    'kds.manage',
    'inventory.view',
    'menuItems.view',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'schedule.view',
    'timeTracking.view',
    'timeTracking.clock',
    'absence.view',
    'absence.request',
    'internalMessages.view',
    'recipes.view',
    'recipes.update',
  ],
  Bar: [
    'dashboard.view',
    'tables.view',
    'tables.status.update',
    'counter.orders.view',
    'counter.orders.update',
    'counter.pickupDisplay.view',
    'counter.settings.view',
    'orders.view',
    'orders.update',
    'kds.view',
    'kds.manage',
  ],
  Theke: [
    'dashboard.view',
    'tables.view',
    'tables.status.update',
    'counter.orders.view',
    'counter.orders.create',
    'counter.orders.update',
    'counter.orders.pay',
    'counter.orders.complete',
    'counter.orders.cancel',
    'counter.pickupDisplay.view',
    'counter.settings.view',
    'orders.view',
    'orders.create',
    'orders.update',
    'kds.view',
    'kds.manage',
  ],
  Lager: [
    'dashboard.view',
    'locations.view',
    'inventory.view',
    'inventory.create',
    'inventory.update',
    'inventory.delete',
    'inventory.stock.adjust',
    'inventory.inventory.manage',
    'categories.view',
    'categories.create',
    'categories.update',
    'categories.delete',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'schedule.view',
    'timeTracking.view',
    'timeTracking.clock',
    'absence.view',
    'absence.request',
    'internalMessages.view',
    'recipes.view',
    'recipes.costing.view',
    'suppliers.view',
    'suppliers.create',
    'suppliers.update',
    'suppliers.delete',
  ],
  Einkauf: [
    'dashboard.view',
    'inventory.view',
    'inventory.create',
    'inventory.update',
    'inventory.stock.adjust',
    'suppliers.view',
    'suppliers.create',
    'suppliers.update',
    'suppliers.delete',
    'categories.view',
    'categories.create',
    'categories.update',
    'categories.delete',
    'recipes.view',
    'recipes.costing.view',
    'reports.view',
  ],
  Buchhaltung: [
    'dashboard.view',
    'counter.orders.view',
    'counter.reports.view',
    'counter.reports.export',
    'finance.view',
    'accounting.view',
    'reports.view',
    'reports.export',
    'employees.view',
    'employees.export',
    'hrDocuments.view',
    'timeTracking.view',
    'payroll.view',
    'payroll.export',
  ],
  Marketing: [
    'dashboard.view',
    'marketing.view',
    'marketing.update',
    'customers.view',
  ],
  Personalabteilung: [
    'dashboard.view',
    'employees.view',
    'employees.create',
    'employees.update',
    'employees.delete',
    'employees.export',
    'hrDocuments.view',
    'hrDocuments.create',
    'hrDocuments.update',
    'hrDocuments.delete',
    'recruiting.view',
    'recruiting.create',
    'recruiting.update',
    'recruiting.delete',
    'feedback.view',
    'feedback.create',
    'feedback.update',
    'feedback.delete',
    'users.view',
    'schedule.view',
    'schedule.create',
    'schedule.update',
    'schedule.publish',
    'timeTracking.view',
    'timeTracking.clock',
    'timeTracking.correct',
    'absence.view',
    'absence.request',
    'absence.approve',
    'payroll.view',
    'payroll.export',
  ],
  Reinigung: [
    'dashboard.view',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'schedule.view',
    'timeTracking.view',
    'timeTracking.clock',
    'absence.view',
    'absence.request',
    'users.own.view',
    'users.own.update',
  ],
  Eventmanager: [
    'dashboard.view',
    'reservations.view',
    'reservations.create',
    'marketing.view',
  ],
  Kunde: ['dashboard.view', 'users.own.view', 'users.own.update'],
  Tellerwäscher: [
    'dashboard.view',
    'locations.view',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'schedule.view',
    'timeTracking.view',
    'timeTracking.clock',
    'absence.view',
    'absence.request',
    'internalMessages.view',
    'users.own.view',
    'users.own.update',
  ],
};
