export interface PermissionDefinition {
  key: string;
  module: string;
  resource: string;
  action: string;
  description: string;
}

const modules = {
  dashboard: ['view'],
  dailyClosings: ['view', 'manage', 'reopen', 'lock'],
  users: ['view', 'create', 'update', 'delete', 'own.view', 'own.update'],
  roles: ['view', 'create', 'update', 'delete', 'permissions.update'],
  companies: ['view', 'create', 'update'],
  regions: ['view', 'create', 'update'],
  locations: ['view', 'create', 'update', 'delete'],
  tables: ['view', 'create', 'update', 'status.update', 'delete'],
  orders: ['view', 'create', 'update', 'cancel'],
  kds: ['view', 'manage'],
  reservations: ['view', 'create', 'update', 'delete'],
  inventory: [
    'view',
    'create',
    'update',
    'delete',
    'stock.adjust',
    'inventory.manage',
  ],
  suppliers: ['view', 'create', 'update', 'delete'],
  menuItems: ['view', 'create', 'update', 'delete'],
  recipes: [
    'view',
    'create',
    'update',
    'delete',
    'costing.view',
    'report.export',
  ],
  categories: ['view', 'create', 'update', 'delete'],
  tasks: ['view', 'create', 'update', 'delete'],
  employees: ['view', 'create', 'update', 'delete'],
  internalMessages: ['view', 'create'],
  reports: ['view', 'export'],
  analytics: ['view'],
  finance: ['view', 'update'],
  accounting: ['view', 'update'],
  marketing: ['view', 'update'],
  customers: ['view', 'create', 'update', 'delete'],
  settings: ['view', 'update'],
  audit: ['view'],
} satisfies Record<string, string[]>;

export const PERMISSION_DEFINITIONS: PermissionDefinition[] = Object.entries(
  modules,
).flatMap(([module, actions]) =>
  actions.map((action) => ({
    key: `${module}.${action}`,
    module,
    resource: module,
    action,
    description: `${module}.${action}`,
  })),
);

export const ALL_PERMISSIONS = PERMISSION_DEFINITIONS.map(
  (permission) => permission.key,
);

const withoutPermissions = (...deniedPrefixes: string[]): string[] =>
  ALL_PERMISSIONS.filter(
    (permission) =>
      !deniedPrefixes.some((prefix) => permission.startsWith(prefix)),
  );

const companyAdminPermissions = withoutPermissions('settings.update');

const regionAdminPermissions = withoutPermissions(
  'audit.view',
  'companies.create',
  'companies.update',
  'regions.create',
  'regions.update',
  'roles.create',
  'roles.update',
  'roles.delete',
  'roles.permissions.update',
  'settings.update',
  'tables.delete',
);

const regionalleiterPermissions = withoutPermissions(
  'audit.view',
  'companies.',
  'regions.create',
  'regions.update',
  'roles.',
  'settings.',
  'tables.delete',
);

const bereichsleiterPermissions = withoutPermissions(
  'audit.view',
  'companies.',
  'regions.create',
  'regions.update',
  'roles.',
  'settings.',
  'locations.create',
  'locations.delete',
  'tables.delete',
);

const filialleiterPermissions = withoutPermissions(
  'audit.view',
  'companies.',
  'regions.',
  'roles.',
  'settings.',
  'locations.create',
  'locations.delete',
  'tables.delete',
);

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  PlatformAdmin: ['*'],
  'Super Admin': ['*'],
  CompanyAdmin: companyAdminPermissions,
  RegionAdmin: regionAdminPermissions,
  Admin: companyAdminPermissions,
  Regionalleiter: regionalleiterPermissions,
  Bereichsleiter: bereichsleiterPermissions,
  Filialleiter: filialleiterPermissions,
  Restaurantleiter: [
    'dashboard.view',
    'users.view',
    'orders.view',
    'orders.update',
    'kds.view',
    'kds.manage',
    'inventory.view',
    'recipes.view',
    'recipes.costing.view',
    'suppliers.view',
    'reports.view',
    'analytics.view',
    'dailyClosings.view',
    'dailyClosings.manage',
  ],
  Schichtleiter: [
    'dashboard.view',
    'tables.view',
    'tables.status.update',
    'orders.view',
    'orders.update',
    'kds.view',
    'kds.manage',
    'tasks.view',
    'dailyClosings.view',
    'dailyClosings.manage',
  ],
  Service: [
    'dashboard.view',
    'locations.view',
    'tables.view',
    'tables.status.update',
    'orders.view',
    'orders.create',
    'orders.update',
    'reservations.view',
    'reservations.create',
    'kds.view',
    'kds.manage',
    'menuItems.view',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'employees.create',
    'employees.update',
    'internalMessages.view',
    'internalMessages.create',
    'users.own.view',
    'users.own.update',
    'recipes.view',
  ],
  Küche: [
    'dashboard.view',
    'locations.view',
    'tables.view',
    'orders.view',
    'orders.update',
    'kds.view',
    'kds.manage',
    'inventory.view',
    'menuItems.view',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'employees.create',
    'employees.update',
    'internalMessages.view',
    'recipes.view',
    'recipes.update',
  ],
  Bar: [
    'dashboard.view',
    'tables.view',
    'tables.status.update',
    'orders.view',
    'orders.update',
    'kds.view',
    'kds.manage',
  ],
  Theke: [
    'dashboard.view',
    'tables.view',
    'tables.status.update',
    'orders.view',
    'orders.create',
    'orders.update',
    'kds.view',
    'kds.manage',
  ],
  Lager: [
    'dashboard.view',
    'locations.view',
    'inventory.view',
    'inventory.create',
    'inventory.update',
    'inventory.delete',
    'inventory.stock.adjust',
    'inventory.inventory.manage',
    'categories.view',
    'categories.create',
    'categories.update',
    'categories.delete',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'employees.create',
    'employees.update',
    'internalMessages.view',
    'recipes.view',
    'recipes.costing.view',
    'suppliers.view',
    'suppliers.create',
    'suppliers.update',
    'suppliers.delete',
  ],
  Einkauf: [
    'dashboard.view',
    'inventory.view',
    'inventory.create',
    'inventory.update',
    'inventory.stock.adjust',
    'suppliers.view',
    'suppliers.create',
    'suppliers.update',
    'suppliers.delete',
    'categories.view',
    'categories.create',
    'categories.update',
    'categories.delete',
    'recipes.view',
    'recipes.costing.view',
    'reports.view',
  ],
  Buchhaltung: [
    'dashboard.view',
    'finance.view',
    'accounting.view',
    'reports.view',
    'reports.export',
  ],
  Marketing: [
    'dashboard.view',
    'marketing.view',
    'marketing.update',
    'customers.view',
  ],
  Personalabteilung: ['dashboard.view', 'employees.view', 'users.view'],
  Reinigung: [
    'dashboard.view',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'employees.create',
    'employees.update',
    'users.own.view',
    'users.own.update',
  ],
  Eventmanager: [
    'dashboard.view',
    'reservations.view',
    'reservations.create',
    'marketing.view',
  ],
  Kunde: ['dashboard.view', 'users.own.view', 'users.own.update'],
  Tellerwäscher: [
    'dashboard.view',
    'locations.view',
    'tasks.view',
    'tasks.update',
    'employees.view',
    'employees.create',
    'employees.update',
    'internalMessages.view',
    'users.own.view',
    'users.own.update',
  ],
};
